theme: jekyll-theme-minimal
title: Infektionsschutz Kompendium
description: Wissen für Gesundheitsämter
show_downloads: false
github: github.com/jakobschumacher

collections:
  overview:
    output: true
  merkblatt:
    output: true
  interview:
    output: true
  aktion:
    output: true
  fortbildung:
    output: true
  katalog:
    output: true
collections_dir: pages
