theme: jekyll-theme-slate
title: Infektionsschutz Kompendium
description: Infektionswissen für Gesundheitsämter
show_downloads: false
github: github.com/jakobschumacher
repository_url: https://github.com/jakobschumacher/infektionsschutzkompendium
baseurl: /infektionsschutzkompendium
logo: assets/img/logo3.png

collections:
  overview:
    output: true
  merkblatt:
    output: true
  interview:
    output: true
  aktion:
    output: true
  fortbildung:
    output: true
  katalog:
    output: true
collections_dir: pages
